audioBaseUrl: https://storage.googleapis.com/language-explorer-assets
lessons:
  - name: Mandarin
    subtitle: Basics of Mandarin
    path: lessons/mandarin
    descriptionFile: lessons/mandarin/lesson-description.md
    source: lessons/mandarin/mandarin.txt
    target: lessons/mandarin/mandarin-en.txt
    transcription: lessons/mandarin/mandarin-zh.txt
  - name: Sichuanese
    subtitle: Mandarin words with Sichuanese pronunciation
    path: lessons/sichuanese
    source: lessons/sichuanese/sichuanese.txt
    target: lessons/sichuanese/sichuanese-en.txt
    transcription: lessons/sichuanese/sichuanese-zh.txt
