audioBaseUrl: ""

lessons:
  - name: "Mandarin"
    subtitle: "Basics of Mandarin"
    path:           "lessons/mandarin"       # used for audio lookup
    descriptionFile: "lessons/mandarin/lesson-description.md"
    source:         "lessons/mandarin/mandarin.txt" # smaller text under characters
    target:         "lessons/mandarin/mandarin-en.txt" # right side translation
    transcription:  "lessons/mandarin/mandarin-zh.txt" # larger characters
  - name: "Sichuanese"
    subtitle: "Mandarin words with Sichuanese pronunciation"
    path:           "lessons/sichuanese"       # used for audio lookup
    source:         "lessons/sichuanese/sichuanese.txt" # smaller text under characters
    target:         "lessons/sichuanese/sichuanese-en.txt" # right side translation
    transcription:  "lessons/sichuanese/sichuanese-zh.txt" # larger characters
